apiVersion: v1
kind: Service
metadata: 
 name: server-clusterip-service
 labels:
    test: server-clusterip-service
spec:
  type: ClusterIP
  clusterIP: 10.96.0.2
  ports:
    - targetPort: 8090
      port: 80
  selector:
    app: goserver        