apiVersion: v1
kind: Service
metadata: 
 name: test-load-balancer-service
 labels:
    test: myloadbalancerservice
spec:
  type: LoadBalancer
  ports:
    - targetPort: 9090
      port: 9090
  selector:
    app: goclient      