apiVersion: v1
kind: Pod
metadata:
  name: test-pv-pod
spec:
  volumes:
    - name: test-pv-storage
      persistentVolumeClaim:
        claimName: test-pv-claim
  containers:
    - name: test-pv-container
      image: srokade/volumeserver:volumeserver
      volumeMounts:
        - mountPath: "/serverdata"
          name: test-pv-storage

